@startuml 发货状态

left to right direction

[*] --> 未创建
未创建 -r-> 未发货 : 创建物流单
未发货 --> 已发货 : 发货
未发货 --> 配货中 : 配货
未发货 --> 部分发货 : 部分发货
部分发货 --> 部分收货 : 部分收货
部分发货 --> 已发货 : 发货
部分发货 --> 已退货 : 退货
部分收货 --> 已退货 : 退货
部分收货 --> 已收货 : 收货
配货中 --> 已发货 : 发货
已发货 --> 已收货 : 收货
已发货 --> 已退货 : 退货
已收货 --> 已退货 : 退货
已退货 --> [*]

@enduml