@startuml 支付状态

left to right direction

[*] --> 未付款
未付款 --> 已付款 : 支付
未付款 --> 已关闭 : 关单
已关闭 -> [*]
未付款 --> 已冻结 : 冻结
已冻结 --> 未付款 : 解冻
已付款 --> 已退款 : 退款
已退款 --> [*]
已付款 --> 交易成功 : 确认收货
交易成功 --> [*]
交易成功 -l-> 已退款 : 退货退款

@enduml